controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_drive_controller:
      type: swerve_drive_controller/SwerveController

swerve_drive_controller:
  ros__parameters:
    front_left_wheel_joint: "fl_wheel_joint"
    front_right_wheel_joint: "fr_wheel_joint"
    rear_left_wheel_joint: "rl_wheel_joint"
    rear_right_wheel_joint: "rr_wheel_joint"

    front_left_axle_joint: "fl_axle_joint"
    front_right_axle_joint: "fr_axle_joint"
    rear_left_axle_joint: "rl_axle_joint"
    rear_right_axle_joint: "rr_axle_joint"

    wheelbase: 0.50
    trackwidth: 0.40
    wheel_radius: 0.05

    # 無限回転モード（制限なし continuous: スリップリング仕様）
    enable_steering_angle_limits: false
    min_steering_angle: -3.141592653589793
    max_steering_angle:  3.141592653589793

    use_stamped_vel: false

    cmd_vel_timeout: 0.5
    odom: "odom"
    base_footprint: "base_footprint"
    enable_odom_tf: true
    open_loop: false
    front_left_velocity_threshold: 20.0
    front_right_velocity_threshold: 20.0
    rear_left_velocity_threshold: 20.0
    rear_right_velocity_threshold: 20.0
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
